namespace GiftOfTheGivers.Functions.Models
{
    // What the web app sends once a donation form is successfully submitted.
    public class TaxCertificateRequest
    {
        public string ReferenceNumber { get; set; } = string.Empty;
        public string DonorName { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public string Currency { get; set; } = "ZAR";
        public string Cause { get; set; } = string.Empty;
        public DateTime DonationDate { get; set; }
    }

    // Dummy certificate handed back to the web app - no real tax authority
    // is involved at prototype stage, but the shape mirrors what a real
    // certificate-issuing service would return.
    public class TaxCertificateResponse
    {
        public string CertificateNumber { get; set; } = string.Empty;
        public string ValidationCode { get; set; } = string.Empty;
        public DateTime IssuedAt { get; set; }
        public string DonorName { get; set; } = string.Empty;
        public decimal Amount { get; set; }
        public string Currency { get; set; } = "ZAR";
        public string Cause { get; set; } = string.Empty;
        public string Message { get; set; } =
            "This is a dummy certificate generated by the Azure Function prototype for academic demonstration purposes only.";
    }
}
